project:
  type: website

website:
  title: "社会科のおもちゃばこ"
  
  
  sidebar:
    style: "docked"  
    search: true
    contents:
      - href: index.qmd
        text: Home
     

      # 他のページを作ったらここに追加します
      # - href: about.qmd
      #   text: About

  # 上部のメニュー
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduce\introduction.qmd
        text: 筆者紹介
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true